---
abstract: 'CPAN Test Dummy for CPAN.pm'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.46
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Test-Dummy-Perl5-Make-CircularPrereq
no_index:
  directory:
    - t
    - inc
requires:
  CPAN::Test::Dummy::Perl5::Make::OptionalPrereq: 0.42
version: 1.00
